spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  application:
    name: credit_history_rest_service
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_history
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      schema: public
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 8084