spring:
  application:
    name: process_service
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver
camunda:
  bpm:
    deployment-resource-pattern: classpath:/bpmn/simple.bpmn
    application:
      delete-upon-undeploy: false
      scan-for-process-definitions: false
      deploy-changed-only: true
      resume-previous-versions: true
      resume-previous-by: a value
    job-execution:
      enabled: true
    metrics:
      enabled: false
      db-reporter-activate: false
camunda.bpm.admin-user:
  id: admin
  password: admin

server:
  port: 8082